### DISCUSSION TITLE
How to access clients from server

### DISCUSSION THREAD

**Discussion by fbucek** [kyl191/ansible-role-openvpn#193] [General]
How to setup OpenVPN to access clients from VPN server.

Everything works as expected but I cannot ping any client from server. 
I can ping client1 from client2.
Info: I have docker installed. 

ansible config:
```
- hosts: openvpn
  become: true
  gather_facts: true
  roles:
    - role: kyl191.openvpn
      clients:
        - client1
        - client2
      openvpn_port: 4300
      openvpn_server_hostname: 1.2.3.4
      openvpn_client_register_dns: false
      openvpn_redirect_gateway: false
      openvpn_client_to_client: true
```
