### ISSUE TITLE
Crontab failed

### ISSUE THREAD

**Issue by Tanis74** [kyl191/ansible-role-openvpn#112]
Centos 7 minimal 2003 don't have installed crontab 

Role application stops on error

`TASK [kyl191.openvpn : Add cron to check every Saturday if the CRL needs to be renewed] *****************************************************************************************************************************
fatal: [vpn-server-01]: FAILED! => {"changed": false, "msg": "Failed to find required executable crontab in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin"}`

Decision
`yum install cronie`

**Comment by kyl191** [comment]
I'd suggest adding the package installation in the pre run, eg
```
- hosts: vpn
  become: yes
  pre_tasks:
    - name: Install crontab
      package:
        name: cronie
        state: present
  roles:
    - role: kyl191.openvpn
      clients: [client1]
      openvpn_sync_certs: true
```
