### ISSUE TITLE
Allow apt version pinning on the installed packages

### ISSUE THREAD

**Issue by utkuozdemir** [kyl191/ansible-role-openvpn#138]
It would be good to be able to pin the openvpn package and the other packages to a specific version to make sure that installations are identical even if new versions of the packages are released. For example:
```
- name: Install openvpn
  package:
   name: "{{ item }}"
   state: present
  with_items:
    - openvpn=2.4.7-1ubuntu2
    - openssl=1.1.1f-1ubuntu2.2
```
