### ISSUE TITLE
sync_certs fails

### ISSUE THREAD

**Issue by eclivus** [kyl191/ansible-role-openvpn#146]
Hello,

I tried to provision openvpn on Amazon Linux 2 AMI (ami-02f9ea74050d6f812) and Centos 7.

```
- hosts: all
  gather_facts: true
  roles:
    - role: kyl191.openvpn
      openvpn_sync_certs: true # BUG
      openvpn_duplicate_cn: true
      openvpn_server_hostname: xxx.xxx.com
      become: true
      clients:
        - victor
        - celine
      openvpn_push:
        - dhcp-option DNS X.X.X.X
```

When enabling openvpn_sync_certs I have an error when there is no client and another if there are already clients.
Error when there are no clients yet:
```

TASK [kyl191.openvpn : Get existing certs] *******************************************************************************************************
fatal: [172.31.11.150]: FAILED! => {"changed": true, "cmd": "set -o pipefail\nls /etc/openvpn/keys | grep '\\.csr' | grep -v 'server.csr' | sort | cut -f1 -d'.' > /tmp/existing-certs\n", "delta": "0:00:00.006633", "end": "2021-05-10 09:10:32.823718", "msg": "non-zero return code", "rc": 1, "start": "2021-05-10 09:10:32.817085", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

```
Error when there are already clients:
```
TASK [kyl191.openvpn : Get difference between 'clients' variable and existing certs] ***********************************************************************************************************************
fatal: [172.31.15.142]: FAILED! => {"changed": true, "cmd": "set -o pipefail\nsort -o /tmp/client-list /tmp/client-list\ndiff /tmp/client-list /tmp/existing-certs | grep '>' | awk '{print $2}'\n", "delta": "0:00:00.021649", "end": "2021-05-10 07:55:40.363357", "msg": "non-zero return code", "rc": 1, "start": "2021-05-10 07:55:40.341708", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
```

Cheers and thanks
