### ISSUE TITLE
Test latest changes on AWS 

### ISSUE THREAD

**Issue by kyl191** [kyl191/ansible-role-openvpn#26]
Ubuntu (https://cloud-images.ubuntu.com/locator/ec2/):
16.10: ubuntu/images/hvm-ssd/ubuntu-yakkety-16.10-amd64-server-20170103 - ami-4ae1fb5d
16.04: ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20170202 - ami-f0768de6
14.04: ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-20170202.1 - ami-af22d9b9
12.04: ubuntu/images/hvm-ssd/ubuntu-precise-12.04-amd64-server-20170202 - ami-a49e65b2

Debian (user: admin, https://wiki.debian.org/Cloud/AmazonEC2Image/Jessie):
8.7: debian-jessie-amd64-hvm-2017-01-15-1221-ebs - ami-b14ba7a7
7.8: debian-wheezy-amd64-hvm-2015-01-28-ebs - ami-e0efab88

Fedora:
25: Fedora-Cloud-Base-25-20170214.0.x86_64-us-east-1-HVM-gp2-0 - ami-ef70bff9
24: Fedora-Cloud-Base-24-20161207.0.x86_64-us-east-1-HVM-gp2-0 - ami-a11c1ab6
23: Fedora-Cloud-Base-23-20160626.x86_64-us-east-1-HVM-gp2-0 - ami-ec458981

CentOS:
7 (1602): https://aws.amazon.com/marketplace/pp/B00O7WM7QW
6 (2014-09-29): https://aws.amazon.com/marketplace/pp/B00A6KUVBW
Other point releases not available?

**Comment by kyl191** [comment]
Ubuntu 14.04 installs 2.3.2, which doesn't support tls-min-version:
```
root@ip-172-30-0-175:/etc/openvpn# openvpn --config openvpn_udp_1194.conf
Options error: Unrecognized option or missing parameter(s) in openvpn_udp_1194.conf:15: tls-version-min (2.3.2)
Use --help for more information.
root@ip-172-30-0-175:/etc/openvpn# openvpn --version
OpenVPN 2.3.2 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [eurephia] [MH] [IPv6] built on Dec  1 2014
Originally developed by James Yonan
Copyright (C) 2002-2010 OpenVPN Technologies, Inc. <sales@openvpn.net>
Compile time defines: .. elided ..
root@ip-172-30-0-175:/etc/openvpn# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

```

**Comment by kyl191** [comment]
Fedora 25 (Fedora-Cloud-Base-25-20170214.0.x86_64-us-east-1-HVM-gp2-0 (ami-ef70bff9)) works fine, as does Ubuntu 16.04 with the UFW changes in #27 

Ubuntu 16.10 is fighting against being run in docker, systemd is somehow not installed.

**Comment by kyl191** [comment]
14.04 doesn't work with CI, but works on AWS.

16.10 added to CI.

**Comment by kyl191** [comment]
Inventory:
```
overarch["fedora"] = {
    "hosts": ["52.90.230.44", "174.129.77.124", "54.89.14.38"],
    "vars": {
        "ansible_user": "fedora",
        "ansible_become": True,
        "remote_user": "root",
        "ansible_python_interpreter": "/usr/bin/python3"
    }
}

overarch["debian"] = {
    "hosts": ["54.161.120.124", "54.157.27.185"],
    "vars": {
        "ansible_user": "admin",
        "ansible_become": True,
        "remote_user": "root",

    }
}

overarch["ubuntu"] = {
    "hosts": ["52.90.65.247", "52.55.26.20"],
    "vars": {
        "ansible_user": "ubuntu",
        "ansible_become": True,
        "remote_user": "root"
    }
}

overarch["ubuntu3"] = {
    "hosts": ["54.152.63.131", "52.203.77.150"],
    "vars": {
        "ansible_user": "ubuntu",
        "ansible_become": True,
        "remote_user": "root",
        "ansible_python_interpreter": "/usr/bin/python3"
    }
}

overarch["vpn"] = {"children": ["ubuntu", "ubuntu3", "debian", "fedora"], "hosts":[]}
```
Playbook:
```
- hosts: vpn
  become: yes
  pre_tasks:
    - name: Install firewalld for Fedora
      package:
        name: firewalld
        state: present
      when: ansible_distribution == "Fedora"

    - name: Install ufw for Debian
      package:
        name: ufw
        state: present
        update_cache: yes
      when: ansible_distribution == "Debian"

    - name: Install python2 for Ubuntu >=16.*
      package:
        name: python
        state: present
      when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 16

    - name: Reset python interpreter for Ubuntu >=16.*
      set_fact:
        ansible_python_interpreter: /usr/bin/python
      when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 16

    - name: Disable modern TLS on Ubuntu <= 14.04 and Debian 7
      set_fact:
        openvpn_use_modern_tls: false
      when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int <= 14 or ansible_distribution == "Debian" and ansible_distribution_major_version|int == 7

    - name: Disable verify CN on Ubuntu 12.04 and Debian 7
      set_fact:
        openvpn_verify_cn: false
      when: ansible_distribution_release == "precise" or ansible_distribution == "Debian" and ansible_distribution_major_version|int == 7

  roles:
    - {role: kyl191.openvpn,
      clients: [desktop],
      openvpn_generate_unified_client_conf: true}
```
