### ISSUE TITLE
leverage multiple server config

### ISSUE THREAD

**Issue by Sispheor** [kyl191/ansible-role-openvpn#34]
Currently the role can handle only one configuration per server.

It would be usefull to allow the configuration of multiple config.

**Comment by kyl191** [comment]
What would this look like? Multiple ports, protocols?

**Comment by Sispheor** [comment]
yes, the user would have to change the port.
The yaml config would become a list of server config
```yml
servers:
  - name: server1
    openvpn_port: 1194
    openvpn_proto: udp
  - name: server2
    openvpn_port: 1195
    openvpn_proto: udp
```

I think about that because OpenVPN seems not allow to use a double backend authentication in the same time.
So if you want to allow your users to access the network via certificate or LDAP, we need 2 servers.
