### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by lucasmaurice** [kyl191/ansible-role-openvpn#89]
There is a bad var usage in the task `server_keys.yml`.

```
fatal: [vpn-test.mylab.com]: FAILED! => {"msg": "The conditional check 'file_result.state == 'absent'' failed. The error was: error while evaluating conditional (file_result.state == 'absent'): 'dict object' has no attribute 'state'\n\nThe error appears to be in '/home/lmaurice/ws/infra/ansible-infrastructure/galaxy_roles/openvpn/tasks/server_keys.yml': line 137, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: create certificate revocation list database if required\n  ^ here\n"}
```

I solved the problem replacing in [tasks/server_keys.yml](https://github.com/kyl191/ansible-role-openvpn/blob/5821e7a9ca1e326b8cd19edb0c1856902e841a04/tasks/server_keys.yml#L137) line *137* :
This
```
- name: create certificate revocation list database if required
  file:
    path: "{{openvpn_key_dir}}/index.txt"
    state: touch
  when: file_result.state == 'absent'
```
By this
```
- name: create certificate revocation list database if required
  file:
    path: "{{openvpn_key_dir}}/index.txt"
    state: touch
  when: '"absent" in file_result'
```
